Add collapsible table logic
fiaisis/frontend pull request #125
Opened 2024-05-09 08:36 UTC by Dagonite

Closes # 

## Description

2024-05-10 09:26 UTC, Pasarus requested changes
This looks phenomenal and exactly how I envisioned it.

Only a couple issues that should be easily resolvable:
- When sorting by title the application seems to crash, we don't need to sort by title so feel free to turn this off.
- Can we swap the reduction start/end with the run start/end so the reduction details are in the drop down and the run details are in the main table?
- In the event that a run fails, it still says "Reduction outputs" where it should say stacktrace output (Even though we don't presently record this data fully)
- Could we give the values in the Run Details and Reduction Inputs a font-weight: 500; to make them "slightly" more bold than normal to reduce "noise"?
- Before merging I'd like to disable the View button until the feature is implemented, could both buttons get a tooltip saying "Work in progress..." or "Feature coming soon"?

Really happy with this so far, great work!

2024-05-10 09:31 UTC, Dagonite commented
>When sorting by title the application seems to crash, we don't need to sort by title so feel free to turn this off.

Yes I had assumed sorting by title would be added to the API later but I'll remove it if it's not needed.

>Can we swap the reduction start/end with the run start/end so the reduction details are in the drop down and the run details are in the main table?

Yes will do.

>In the event that a run fails, it still says "Reduction outputs" where it should say stacktrace output (Even though we don't presently record this data fully)

Yeah I'll change this.

>Could we give the values in the Run Details and Reduction Inputs a font-weight: 500; to make them "slightly" more bold than normal to reduce "noise"?

Will do.

>Before merging I'd like to disable the View button until the feature is implemented, could both buttons get a tooltip saying "Work in progress..." or "Feature coming soon"?

Yes. And currently have a tooltip in place for the disabled "Download" button.

2024-05-13 09:07 UTC, Pasarus requested changes
Would it be possible to move this here?
![image](https://github.com/fiaisis/frontend/assets/24723609/c1c47cfe-5b07-4e13-8edf-a89ac1c4fd65)

Only other thing that I'd like to comment on/change is that it doesn't seem obvious to a user that the reduction inputs is scrollable notable problem on MARI, not sure if there is a good solution to this?

2024-05-13 09:30 UTC, Dagonite commented on src/ReductionHistory.tsx
> +                    Reduction end: {formatDateTime(reduction.reduction_start)}
Oopsy

2024-05-13 12:33 UTC, Pasarus approved these changes
Thank you for this! It looks really good.

2024-05-13 12:33 UTC, merged