Value editor page
fiaisis/frontend pull request #155
Opened 2024-05-23 09:31 UTC by Dagonite

Closes # 

## Description

2024-05-24 13:24 UTC, Pasarus requested changes
Code looks fine on the first run through. Quite happy with how it looks and here is a sumarised list of issues discussed in the impromptu meeting.

- Could we change this background colour:
![image](https://github.com/fiaisis/frontend/assets/24723609/cf1935bf-2b88-416c-a60c-60a5cf5a201d)
To:
![image](https://github.com/fiaisis/frontend/assets/24723609/0ecd6e0d-492d-4775-bf3a-231985c049bd)

- Would it be possible to move the Run button to the right of the runner version drop down?
- Can the runner version drop down be made more compact?
- Can we remove the text before the run button replacing Run text with in the button with: "Rerun with new input" then a tooltip explaining it will take the values from the scrip/User inputs (I really like the user inputs name by the way vs the old GUI inputs)
- Can we hide the titlebar, nav menu, and footer? Basically hiding away all links to navigate away, we would expect users to close the window.
- Can we have just 2 tabs, script and user inputs, no longer is there a requirement at least for now to have multiple tabs (this is only known whilst I think about it).

2024-05-29 08:18 UTC, Dagonite commented
> * Can we hide the titlebar, nav menu, and footer? Basically hiding away all links to navigate away, we would expect users to close the window.

Unsure how to implement this so might be best to leave for another PR for now

2024-05-29 08:22 UTC, Dagonite commented
Here is the updated page.
![image](https://github.com/fiaisis/frontend/assets/47388695/14167aba-70e9-4d7c-bf69-ed96c4d8361d)

2024-06-03 07:59 UTC, Pasarus approved these changes

2024-06-03 07:59 UTC, merged